name: fu_uber
description: A Uber clone in flutter with provider

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  location: ^6.0.2
  pin_code_text_field: ^1.8.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sliding_up_panel: ^2.0.0+1

  http: any
  vector_math: any
  connectivity_plus: ^6.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
