name: fu_uber
description: A Uber clone in flutter with provider











version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
#  provider: ^3.1.0+1
#  google_maps_flutter: ^0.5.21+8
#  location: ^2.3.5
#  geolocator: ^5.1.0
#  google_maps_webservice: ^0.0.14
#  pin_code_text_field: ^1.4.0
#  shared_preferences: ^0.5.4
#  sliding_up_panel: ^0.3.6
#  carousel_slider: ^1.3.0
#  connectivity: ^0.4.5+2
#  flutter_spinkit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
